In [1]:
import pandas as pd
import sys
import os

In [2]:
# simple stacking function

def simple_stack(stack_rows, df):
    df = df.copy()
    df.drop(columns = [0], inplace = True)

    rows_to_remove = df.shape[0] % stack_rows
    new_row_count = df.shape[0] // stack_rows

    df.reset_index(drop = True, inplace = True)
    df.drop(df.tail(rows_to_remove).index, inplace = True)

    #print("df shape:", df.shape)
    new_columns = []
    for i in range(stack_rows):
        new_columns.extend([f"{col}_{i}" for col in df.columns])


    stack_df = pd.DataFrame(columns = new_columns)

    #print(len(stack_df.columns))
    #print(rows_to_remove)
    #print(new_row_count)

    for i in range(new_row_count):
        #print(f"block = {i*stack_rows} to {(i+1) * stack_rows}")
        block = df.iloc[i*stack_rows: (i+1) * stack_rows].values.flatten()
        #print("block len =", len(block))
        stack_df.loc[i] = block

    return stack_df

In [3]:
def extract_ids(filename):
    parts = filename.split("_")

    participant_id = int(parts[1])
    test_id = int(parts[2].split(".")[0])

    return participant_id, test_id

In [9]:
def progress_bar(i, stress_files, stress_file, bar_len = 50, fill='█'):

    progress = ((i+1) / len(stress_files) ) * 100

    bar_fill = int(progress // 2)
    
    bar = bar_fill * fill + "-" * (bar_len - bar_fill)

    print(f"\rReading: {stress_file} |{bar}| {progress:.1f}%", end = "")

In [89]:
stress_path = fr"datasets\2019_stress_detection_dataset\STRESS"
calm_path = fr"datasets\2019_stress_detection_dataset\CALM"

In [90]:
calm_files = os.listdir(calm_path)
calm_files = sorted(calm_files, key = extract_ids)

stress_files = os.listdir(stress_path)
stress_files = sorted(stress_files, key = extract_ids)

In [91]:
wanted_columns = [0]
wanted_columns.extend([i for i in range(7, 43)])

In [92]:
# total calm data
# Initialize the DataFrame
calm_df = pd.DataFrame()


for i, calm_file in enumerate(calm_files):
    progress_bar(i, calm_files, calm_file)
   
    temp = pd.read_csv(os.path.join(calm_path, calm_file), sep=";", header=None)
    temp = temp[wanted_columns]
    calm_df = pd.concat([calm_df, temp], axis=0)
   
calm_df

Reading: CALM_110_7.csv |██████████████████████████████████████████████████| 100.0%

,0,7,8,9,10,11,12,13,14,15,...,33,34,35,36,37,38,39,40,41,42
0,1,-1.398295,4.552336,8.461134,9.709263,-1.573943,4.585593,8.524402,9.806650,0.175647,...,0.255662,0.003678,-0.300669,0.918815,0.174533,1.015117,33.908630,-28.277462,-9.235774,45.107754
1,1,-1.593871,4.467315,8.753821,9.956240,-1.543731,4.495955,8.577510,9.806650,-0.050140,...,0.250321,0.002873,-0.303881,0.919232,0.174533,1.015117,33.908630,-28.277462,-9.235774,45.107754
2,1,-1.593871,4.467315,8.753821,9.956240,-1.543731,4.495955,8.577510,9.806650,-0.050140,...,0.250321,0.002873,-0.303881,0.919232,0.174533,1.015117,34.351746,-27.661564,-9.056985,45.024810
3,1,-1.669115,4.492037,8.941505,10.144695,-1.528073,4.447081,8.605744,9.806650,-0.141042,...,0.250321,0.002873,-0.303881,0.919232,0.174533,1.015117,34.698883,-27.327988,-8.964363,45.068737
4,1,-1.669115,4.492037,8.941505,10.144695,-1.528073,4.447081,8.605744,9.806650,-0.141042,...,0.250321,0.002873,-0.303881,0.919232,0.174533,1.015117,34.698883,-27.327988,-8.964363,45.068737
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1175,110,0.292102,6.706364,7.491686,10.059125,0.214472,6.697370,7.160274,9.806644,0.077630,...,0.228946,0.287248,0.745513,0.556130,0.000000,0.999999,253.035060,-43.073948,1.715667,256.680850
1176,110,0.071828,6.775798,7.360001,10.004309,0.180925,6.803418,7.060531,9.806646,-0.109097,...,0.231031,0.294343,0.744446,0.552979,0.000000,0.999999,252.861080,-43.928130,1.467874,256.652620
1177,110,0.071828,6.775798,7.360001,10.004309,0.180925,6.803418,7.060531,9.806646,-0.109097,...,0.231031,0.294343,0.744446,0.552979,0.000000,0.999999,252.861080,-43.928130,1.467874,256.652620
1178,110,0.172388,7.101419,6.143709,9.391753,0.118522,6.852414,7.014319,9.806645,0.053866,...,0.229483,0.299511,0.744744,0.550441,0.000000,0.999999,252.706180,-44.326942,0.968044,256.566220
1179,110,0.172388,7.101419,6.143709,9.391753,0.118522,6.852414,7.014319,9.806645,0.053866,...,0.229483,0.299511,0.744744,0.550441,0.000000,0.999999,252.706180,-44.326942,0.968044,256.566220

In [ ]:
# dropping CALM duplicates
#calm_df.drop_duplicates(inplace = True)
#calm_df

In [93]:
# total stress data
# Initialize the DataFrame
stress_df = pd.DataFrame()


for i, stress_file in enumerate(stress_files):
    progress_bar(i, stress_files, stress_file)
   
    temp = pd.read_csv(os.path.join(stress_path, stress_file), sep=";", header=None)
    temp = temp[wanted_columns]
    stress_df = pd.concat([stress_df, temp], axis=0)
   
stress_df

Reading: STRESS_110_7.csv |██████████████████████████████████████████████████| 100.0%

,0,7,8,9,10,11,12,13,14,15,...,33,34,35,36,37,38,39,40,41,42
0,1,-0.505169,4.584610,8.654279,9.806650,-0.505169,4.584610,8.654279,9.806650,0.000000,...,0.265109,-0.018235,-0.291391,0.918954,0.174533,1.015117,33.315735,-30.103119,-6.949028,45.435944
1,1,-0.505169,4.584610,8.654279,9.806650,-0.505169,4.584610,8.654279,9.806650,0.000000,...,0.265109,-0.018235,-0.291391,0.918954,0.174533,1.015117,33.315735,-30.103119,-6.949028,45.435944
2,1,-0.505169,4.584610,8.654279,9.806650,-0.505169,4.584610,8.654279,9.806650,0.000000,...,0.265109,-0.018235,-0.291391,0.918954,0.174533,1.015117,36.269745,-27.845741,-2.123154,45.775402
3,1,-0.315210,4.459319,8.487139,9.592518,-0.363312,4.577469,8.665169,9.806649,0.048103,...,0.234221,-0.057790,-0.306295,0.920860,0.174533,1.015117,36.269745,-27.845741,-2.123154,45.775402
4,1,-0.315210,4.459319,8.487139,9.592518,-0.363312,4.577469,8.665169,9.806649,0.048103,...,0.234221,-0.057790,-0.306295,0.920860,0.174533,1.015117,36.269745,-27.845741,-2.123154,45.775402
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1009,110,0.114925,8.008849,5.528380,9.732310,-0.005215,7.989526,5.686626,9.806643,0.120140,...,0.339453,0.307952,0.596749,0.658655,0.000000,0.999999,275.657600,-54.558193,-0.037395,281.004820
1010,110,0.134079,8.157294,5.676825,9.939103,0.011862,7.987276,5.689775,9.806643,0.122218,...,0.340136,0.306936,0.596476,0.659024,0.000000,0.999999,275.678400,-54.535530,0.085088,281.020840
1011,110,0.134079,8.157294,5.676825,9.939103,0.011862,7.987276,5.689775,9.806643,0.122218,...,0.340136,0.306936,0.596476,0.659024,0.000000,0.999999,275.678400,-54.535530,0.085088,281.020840
1012,110,0.134079,8.157294,5.676825,9.939103,0.011862,7.987276,5.689775,9.806643,0.122218,...,0.340136,0.306936,0.596476,0.659024,0.000000,0.999999,275.678400,-54.535530,0.085088,281.020840
1013,110,0.134079,8.157294,5.676825,9.939103,0.011862,7.987276,5.689775,9.806643,0.122218,...,0.340136,0.306936,0.596476,0.659024,0.000000,0.999999,275.678400,-54.535530,0.085088,281.020840

In [ ]:
# dropping CALM duplicates
#stress_df.drop_duplicates(inplace = True)
#stress_df

In [94]:
calm_df.drop(columns = [0], inplace = True)
stress_df.drop(columns = [0], inplace = True)

calm_df["Target"] = 0
stress_df["Target"] = 1

combined = pd.concat([calm_df, stress_df], axis = 0, ignore_index=True)
combined

,7,8,9,10,11,12,13,14,15,16,...,34,35,36,37,38,39,40,41,42,Target
0,-1.398295,4.552336,8.461134,9.709263,-1.573943,4.585593,8.524402,9.806650,0.175647,-0.033257,...,0.003678,-0.300669,0.918815,0.174533,1.015117,33.908630,-28.277462,-9.235774,45.107754,0
1,-1.593871,4.467315,8.753821,9.956240,-1.543731,4.495955,8.577510,9.806650,-0.050140,-0.028640,...,0.002873,-0.303881,0.919232,0.174533,1.015117,33.908630,-28.277462,-9.235774,45.107754,0
2,-1.593871,4.467315,8.753821,9.956240,-1.543731,4.495955,8.577510,9.806650,-0.050140,-0.028640,...,0.002873,-0.303881,0.919232,0.174533,1.015117,34.351746,-27.661564,-9.056985,45.024810,0
3,-1.669115,4.492037,8.941505,10.144695,-1.528073,4.447081,8.605744,9.806650,-0.141042,0.044956,...,0.002873,-0.303881,0.919232,0.174533,1.015117,34.698883,-27.327988,-8.964363,45.068737,0
4,-1.669115,4.492037,8.941505,10.144695,-1.528073,4.447081,8.605744,9.806650,-0.141042,0.044956,...,0.002873,-0.303881,0.919232,0.174533,1.015117,34.698883,-27.327988,-8.964363,45.068737,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1540367,0.114925,8.008849,5.528380,9.732310,-0.005215,7.989526,5.686626,9.806643,0.120140,0.019323,...,0.307952,0.596749,0.658655,0.000000,0.999999,275.657600,-54.558193,-0.037395,281.004820,1
1540368,0.134079,8.157294,5.676825,9.939103,0.011862,7.987276,5.689775,9.806643,0.122218,0.170018,...,0.306936,0.596476,0.659024,0.000000,0.999999,275.678400,-54.535530,0.085088,281.020840,1
1540369,0.134079,8.157294,5.676825,9.939103,0.011862,7.987276,5.689775,9.806643,0.122218,0.170018,...,0.306936,0.596476,0.659024,0.000000,0.999999,275.678400,-54.535530,0.085088,281.020840,1
1540370,0.134079,8.157294,5.676825,9.939103,0.011862,7.987276,5.689775,9.806643,0.122218,0.170018,...,0.306936,0.596476,0.659024,0.000000,0.999999,275.678400,-54.535530,0.085088,281.020840,1
1540371,0.134079,8.157294,5.676825,9.939103,0.011862,7.987276,5.689775,9.806643,0.122218,0.170018,...,0.306936,0.596476,0.659024,0.000000,0.999999,275.678400,-54.535530,0.085088,281.020840,1

In [95]:
combined.to_csv(fr"datasets\combined.csv", index = False)

In [79]:
# change the stack_secs to make 1, 3, 5, 7 secs stacked
stack_secs = 7
stack_rows = 20 * stack_secs

# stacking CALM and STRESS

In [80]:
# stacking CALM data

In [81]:
par_ids = list(calm_df[0].unique())

calm_stack = pd.DataFrame()
#calm_participant_df = pd.DataFrame()

for id in par_ids:
    progress_bar(id-1, par_ids, id)

    temp = simple_stack(stack_rows, calm_df[calm_df[0] == id])
    calm_stack = pd.concat([calm_stack, temp], axis = 0)

calm_stack["Target"] = 0
calm_stack

Reading: 110 |██████████████████████████████████████████████████| 100.0%

,7_0,8_0,9_0,10_0,11_0,12_0,13_0,14_0,15_0,16_0,...,34_139,35_139,36_139,37_139,38_139,39_139,40_139,41_139,42_139,Target
0,-1.398295,4.552336,8.461134,9.709263,-1.573943,4.585593,8.524402,9.806650,0.175647,-0.033257,...,-0.012136,-0.314447,0.915575,0.174533,1.015117,35.963745,-28.064740,-7.773035,46.275703,0
1,-1.418183,4.523597,8.402903,9.647951,-1.326342,4.571331,8.574039,9.806650,-0.091841,-0.047734,...,-0.009170,-0.297210,0.902373,0.174533,1.015117,33.421265,-34.966670,-9.008575,49.201660,0
2,-1.455751,5.578941,8.023575,9.880362,-1.656077,5.574290,7.896524,9.806651,0.200326,0.004651,...,-0.008698,-0.289737,0.904855,0.174533,1.015117,32.487732,-35.253790,-9.493468,48.871350,0
3,-1.665559,5.701287,8.211971,10.134852,-1.617462,5.582869,7.898467,9.806650,-0.048098,0.118418,...,0.008492,-0.292398,0.904586,0.174533,1.015117,31.466614,-34.966072,-12.063405,48.562330,0
4,-1.977575,5.529060,8.272884,10.145044,-2.049531,5.495997,7.858997,9.806650,0.071956,0.033064,...,-0.006909,-0.298928,0.909996,0.174533,1.015117,33.716890,-32.255360,-9.157461,47.550983,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16,0.067040,8.851634,4.661653,10.004345,0.312379,8.630734,4.645752,9.806639,-0.245340,0.220900,...,0.328730,0.575733,0.636602,0.000000,1.000000,274.969820,-61.656124,2.283319,281.806820,0
17,-0.095771,8.722343,4.812492,9.962355,0.337036,8.580883,4.735502,9.806637,-0.432807,0.141460,...,0.211467,0.704514,0.629542,0.000000,0.999999,262.097050,-37.808907,6.273498,264.884370,0
18,1.599376,5.446975,8.162083,9.942190,1.025798,5.948734,7.728560,9.806647,0.573577,-0.501759,...,0.270472,0.736015,0.567048,0.000000,0.999999,254.016160,-43.165720,5.068534,257.707550,0
19,1.041510,6.768615,6.347222,9.337351,0.606147,6.687072,7.147443,9.806645,0.435363,0.081543,...,0.265351,0.756306,0.553849,0.000000,0.999999,251.585940,-40.626870,3.559918,254.869960,0
20,0.203513,6.608199,6.371165,9.181582,0.439011,6.415616,7.403881,9.806646,-0.235498,0.192583,...,0.250429,0.748344,0.569398,0.000000,0.999999,253.485260,-39.576620,4.430359,256.594450,0

In [82]:
# stacking stress data

In [83]:
# stacking stress data
par_ids = list(stress_df[0].unique())

stress_stack = pd.DataFrame()
#calm_participant_df = pd.DataFrame()

for id in par_ids:
    progress_bar(id-1, par_ids, id)

    temp = simple_stack(stack_rows, stress_df[stress_df[0] == id])
    stress_stack = pd.concat([stress_stack, temp], axis = 0)

stress_stack["Target"] = 1
stress_stack

Reading: 110 |██████████████████████████████████████████████████| 100.0%

,7_0,8_0,9_0,10_0,11_0,12_0,13_0,14_0,15_0,16_0,...,34_139,35_139,36_139,37_139,38_139,39_139,40_139,41_139,42_139,Target
0,-0.505169,4.584610,8.654279,9.806650,-0.505169,4.584610,8.654279,9.806650,0.000000,0.000000,...,-0.064058,-0.316917,0.915390,0.174533,1.015117,37.500000,-28.862532,-2.303946,47.377250,1
1,-0.085417,4.714683,9.108461,10.256685,-0.394233,4.729940,8.581530,9.806650,0.308816,-0.015256,...,-0.068264,-0.312688,0.912791,0.174533,1.015117,37.288605,-30.410400,-1.951592,48.156420,1
2,-0.378615,4.942314,8.484178,9.826042,-0.333967,4.961153,8.452563,9.806650,-0.044648,-0.018838,...,-0.055422,-0.290319,0.921692,0.174533,1.015117,34.302216,-29.722795,-2.505852,45.457294,1
3,-0.272145,4.909906,9.870202,11.027336,-0.428761,4.857529,8.508287,9.806650,0.156615,0.052377,...,-0.049028,-0.300665,0.913706,0.174533,1.015117,35.261932,-31.489351,-4.136854,47.456260,1
4,-0.649316,5.081270,8.555737,9.972039,-0.707442,5.109060,8.340708,9.806650,0.058125,-0.027790,...,-0.052044,-0.308344,0.915853,0.174533,1.015117,36.304504,-29.623785,-3.438893,46.983100,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25,0.114925,8.379962,4.738270,9.627470,0.530584,8.294251,5.205199,9.806642,-0.415659,0.085711,...,0.293317,0.589791,0.655726,0.000000,0.999999,274.967100,-56.085250,3.485832,280.650330,1
26,0.720677,8.193209,5.537958,9.915494,0.501175,8.137017,5.450508,9.806643,0.219502,0.056191,...,0.280312,0.587139,0.656550,0.000000,0.999999,274.653300,-56.126293,5.507070,280.383500,1
27,0.114925,7.738296,6.735095,10.259432,0.654423,8.079184,5.519845,9.806640,-0.539498,-0.340888,...,0.311203,0.600716,0.647899,0.000000,0.999999,273.955630,-55.837902,1.196095,279.590760,1
28,-0.232245,8.188420,5.430215,9.828092,0.135739,8.174894,5.415065,9.806643,-0.367984,0.013526,...,0.296189,0.595633,0.663372,0.000000,0.999999,275.835450,-53.851140,1.082287,281.045040,1
29,-0.134079,7.968146,6.019207,9.987001,0.227677,7.983788,5.690116,9.806637,-0.361756,-0.015641,...,0.311664,0.607216,0.650076,0.000000,0.999999,273.896360,-54.364532,0.028544,279.239530,1

In [84]:
# combining them and saving the stacking

In [85]:
combined_stacked = pd.concat([calm_stack, stress_stack], axis = 0, ignore_index= True)
combined_stacked

,7_0,8_0,9_0,10_0,11_0,12_0,13_0,14_0,15_0,16_0,...,34_139,35_139,36_139,37_139,38_139,39_139,40_139,41_139,42_139,Target
0,-1.398295,4.552336,8.461134,9.709263,-1.573943,4.585593,8.524402,9.806650,0.175647,-0.033257,...,-0.012136,-0.314447,0.915575,0.174533,1.015117,35.963745,-28.064740,-7.773035,46.275703,0
1,-1.418183,4.523597,8.402903,9.647951,-1.326342,4.571331,8.574039,9.806650,-0.091841,-0.047734,...,-0.009170,-0.297210,0.902373,0.174533,1.015117,33.421265,-34.966670,-9.008575,49.201660,0
2,-1.455751,5.578941,8.023575,9.880362,-1.656077,5.574290,7.896524,9.806651,0.200326,0.004651,...,-0.008698,-0.289737,0.904855,0.174533,1.015117,32.487732,-35.253790,-9.493468,48.871350,0
3,-1.665559,5.701287,8.211971,10.134852,-1.617462,5.582869,7.898467,9.806650,-0.048098,0.118418,...,0.008492,-0.292398,0.904586,0.174533,1.015117,31.466614,-34.966072,-12.063405,48.562330,0
4,-1.977575,5.529060,8.272884,10.145044,-2.049531,5.495997,7.858997,9.806650,0.071956,0.033064,...,-0.006909,-0.298928,0.909996,0.174533,1.015117,33.716890,-32.255360,-9.157461,47.550983,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8963,0.114925,8.379962,4.738270,9.627470,0.530584,8.294251,5.205199,9.806642,-0.415659,0.085711,...,0.293317,0.589791,0.655726,0.000000,0.999999,274.967100,-56.085250,3.485832,280.650330,1
8964,0.720677,8.193209,5.537958,9.915494,0.501175,8.137017,5.450508,9.806643,0.219502,0.056191,...,0.280312,0.587139,0.656550,0.000000,0.999999,274.653300,-56.126293,5.507070,280.383500,1
8965,0.114925,7.738296,6.735095,10.259432,0.654423,8.079184,5.519845,9.806640,-0.539498,-0.340888,...,0.311203,0.600716,0.647899,0.000000,0.999999,273.955630,-55.837902,1.196095,279.590760,1
8966,-0.232245,8.188420,5.430215,9.828092,0.135739,8.174894,5.415065,9.806643,-0.367984,0.013526,...,0.296189,0.595633,0.663372,0.000000,0.999999,275.835450,-53.851140,1.082287,281.045040,1
8967,-0.134079,7.968146,6.019207,9.987001,0.227677,7.983788,5.690116,9.806637,-0.361756,-0.015641,...,0.311664,0.607216,0.650076,0.000000,0.999999,273.896360,-54.364532,0.028544,279.239530,1

# saving the csv

In [86]:
combined_stacked.to_csv(fr"datasets\nodup_combined_{stack_secs}sec.csv", index = False)