In [1]:
import pandas as pd

# old shape

In [2]:
df = pd.read_csv(r"old_files\old_data\with duplicates\combined.csv")
df1 = pd.read_csv(r"old_files\old_data\with duplicates\combined_1sec.csv")
df3 = pd.read_csv(r"old_files\old_data\with duplicates\combined_3sec.csv")
df5 = pd.read_csv(r"old_files\old_data\with duplicates\combined_5sec.csv")
df7 = pd.read_csv(r"old_files\old_data\with duplicates\combined_7sec.csv")

In [ ]:
shapes = {"Combined (old | duplicates)": [df.shape[0], df.shape[1], df.shape[0] * df.shape[1], df["target"].value_counts().get(0, 0), df["target"].value_counts().get(1, 0)],
          "1 Sec (old | duplicates)": [df1.shape[0], df1.shape[1], df1.shape[0] * df1.shape[1], df1["target"].value_counts().get(0, 0), df1["target"].value_counts().get(1, 0)],
          "3 Sec (old | duplicates)": [df3.shape[0], df3.shape[1], df3.shape[0] * df3.shape[1], df3["target"].value_counts().get(0, 0), df3["target"].value_counts().get(1, 0)],
          "5 Sec (old | duplicates)": [df5.shape[0], df5.shape[1], df5.shape[0] * df5.shape[1], df5["target"].value_counts().get(0, 0), df5["target"].value_counts().get(1, 0)],
          "7 Sec (old | duplicates)": [df7.shape[0], df7.shape[1], df7.shape[0] * df7.shape[1], df7["target"].value_counts().get(0, 0), df7["target"].value_counts().get(1, 0)]}

shapes_df_old_dup = pd.DataFrame.from_dict(shapes, orient='index', columns=["Rows", "Columns", "Product", "Calm_rows", "Stress_rows"])
shapes_df_old_dup

In [ ]:
# no duplicates
df = pd.read_csv(r"old_files\old_data\without duplicates\withoutduplicates_combined.csv")
df1 = pd.read_csv(r"old_files\old_data\without duplicates\withoutduplicates_combined_1sec.csv")
df3 = pd.read_csv(r"old_files\old_data\without duplicates\withoutduplicates_combined_3sec.csv")
df5 = pd.read_csv(r"old_files\old_data\without duplicates\withoutduplicates_combined_5sec.csv")
df7 = pd.read_csv(r"old_files\old_data\without duplicates\withoutduplicates_combined_7sec.csv")
shapes = {"Combined (old | Noduplicates)": [df.shape[0], df.shape[1], df.shape[0] * df.shape[1], df["target"].value_counts().get(0, 0), df["target"].value_counts().get(1, 0)],
          "1 Sec (old | Noduplicates)": [df1.shape[0], df1.shape[1], df1.shape[0] * df1.shape[1], df1["target"].value_counts().get(0, 0), df1["target"].value_counts().get(1, 0)],
          "3 Sec (old | Noduplicates)": [df3.shape[0], df3.shape[1], df3.shape[0] * df3.shape[1], df3["target"].value_counts().get(0, 0), df3["target"].value_counts().get(1, 0)],
          "5 Sec (old | Noduplicates)": [df5.shape[0], df5.shape[1], df5.shape[0] * df5.shape[1], df5["target"].value_counts().get(0, 0), df5["target"].value_counts().get(1, 0)],
          "7 Sec (old | Noduplicates)": [df7.shape[0], df7.shape[1], df7.shape[0] * df7.shape[1], df7["target"].value_counts().get(0, 0), df7["target"].value_counts().get(1, 0)]}
shapes_df_old_nodup = pd.DataFrame.from_dict(shapes, orient='index', columns=["Rows", "Columns", "Product", "Calm_rows", "Stress_rows"])
shapes_df_old_nodup

# new shape

In [6]:
df = pd.read_csv(r"datasets\combined.csv")
df1 = pd.read_csv(r"datasets\combined_1sec.csv")
df3 = pd.read_csv(r"datasets\combined_3sec.csv")
df5 = pd.read_csv(r"datasets\combined_5sec.csv")
df7 = pd.read_csv(r"datasets\combined_7sec.csv")

In [ ]:
shapes_new = {"Combined (new | Duplicates)": [df.shape[0], df.shape[1], df.shape[0] * df.shape[1], df["Target"].value_counts().get(0, 0), df["Target"].value_counts().get(1, 0)],
          "1 Sec (new | Duplicates)": [df1.shape[0], df1.shape[1], df1.shape[0] * df1.shape[1], df1["Target"].value_counts().get(0, 0), df1["Target"].value_counts().get(1, 0)],
          "3 Sec (new | Duplicates)": [df3.shape[0], df3.shape[1], df3.shape[0] * df3.shape[1], df3["Target"].value_counts().get(0, 0), df3["Target"].value_counts().get(1, 0)],
          "5 Sec (new | Duplicates)": [df5.shape[0], df5.shape[1], df5.shape[0] * df5.shape[1], df5["Target"].value_counts().get(0, 0), df5["Target"].value_counts().get(1, 0)],
          "7 Sec (new | Duplicates)": [df7.shape[0], df7.shape[1], df7.shape[0] * df7.shape[1], df7["Target"].value_counts().get(0, 0), df7["Target"].value_counts().get(1, 0)]
          }

shapes_df_new_dup = pd.DataFrame.from_dict(shapes_new, orient='index', columns=["Rows", "Columns", "Product", "Calm_rows", "Stress_rows"])
shapes_df_new_dup

In [8]:
df = pd.read_csv(r"datasets\nodup_combined.csv")
df1 = pd.read_csv(r"datasets\nodup_combined_1sec.csv")
df3 = pd.read_csv(r"datasets\nodup_combined_3sec.csv")
df5 = pd.read_csv(r"datasets\nodup_combined_5sec.csv")
df7 = pd.read_csv(r"datasets\nodup_combined_7sec.csv")

In [ ]:
shapes_new = {"Combined (new | noDuplicates)": [df.shape[0], df.shape[1], df.shape[0] * df.shape[1], df["Target"].value_counts().get(0, 0), df["Target"].value_counts().get(1, 0)],
          "1 Sec (new | noDuplicates)": [df1.shape[0], df1.shape[1], df1.shape[0] * df1.shape[1], df1["Target"].value_counts().get(0, 0), df1["Target"].value_counts().get(1, 0)],
          "3 Sec (new | noDuplicates)": [df3.shape[0], df3.shape[1], df3.shape[0] * df3.shape[1], df3["Target"].value_counts().get(0, 0), df3["Target"].value_counts().get(1, 0)],
          "5 Sec (new | noDuplicates)": [df5.shape[0], df5.shape[1], df5.shape[0] * df5.shape[1], df5["Target"].value_counts().get(0, 0), df5["Target"].value_counts().get(1, 0)],
          "7 Sec (new | noDuplicates)": [df7.shape[0], df7.shape[1], df7.shape[0] * df7.shape[1], df7["Target"].value_counts().get(0, 0), df7["Target"].value_counts().get(1, 0)]
          }
shapes_df_new_nodup = pd.DataFrame.from_dict(shapes_new, orient='index', columns=["Rows", "Columns", "Product", "Calm_rows", "Stress_rows"])
shapes_df_new_nodup

In [12]:
print("Duplicates")

print("Old:-")
display(shapes_df_old_dup)
print("New:-")
display(shapes_df_new_dup)

Duplicates
Old:-

,Rows,Columns,Product,Calm_rows,Stress_rows
Combined (old | duplicates),1540372,43,66235996,704399,835973
1 Sec (old | duplicates),77017,841,64771297,35219,41798
3 Sec (old | duplicates),25671,2521,64716591,11739,13932
5 Sec (old | duplicates),15402,4201,64703802,7043,8359
7 Sec (old | duplicates),11002,5881,64702762,5031,5971

New:-

,Rows,Columns,Product,Calm_rows,Stress_rows
Combined (new | Duplicates),1540372,37,56993764,704399,835973
1 Sec (new | Duplicates),76907,721,55449947,35163,41744
3 Sec (new | Duplicates),25567,2161,55250287,11690,13877
5 Sec (new | Duplicates),15293,3601,55070093,6992,8301
7 Sec (new | Duplicates),10897,5041,54931777,4979,5918

In [13]:
print("No Duplicates")

print("Old:-")
display(shapes_df_old_nodup)
print("New:-")
display(shapes_df_new_nodup)

No Duplicates
Old:-

,Rows,Columns,Product,Calm_rows,Stress_rows
Combined (old | Noduplicates),1279300,44,56289200,583382,695918
1 Sec (old | Noduplicates),63964,861,55073004,29169,34795
3 Sec (old | Noduplicates),21321,2581,55029501,9723,11598
5 Sec (old | Noduplicates),12792,4301,55018392,5833,6959
7 Sec (old | Noduplicates),9137,6021,55013877,4167,4970

New:-

,Rows,Columns,Product,Calm_rows,Stress_rows
Combined (new | noDuplicates),1270732,37,47017084,579488,691244
1 Sec (new | noDuplicates),63430,721,45733030,28919,34511
3 Sec (new | noDuplicates),21071,2161,45534431,9605,11466
5 Sec (new | noDuplicates),12598,3601,45365398,5742,6856
7 Sec (new | noDuplicates),8968,5041,45207688,4085,4883